# Generated by Django 3.2.7 on 2023-07-26 15:58

import apps.transactions.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('wallet_transfer', 'Wallet Transfer'), ('ewallet_transfer', 'eWallet Transfer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('ewallet_name', models.CharField(max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bank_deposit', 'Bank Deposit'), ('card_deposit', 'Card Deposit'), ('ewallet_deposit', 'eWallet Deposit'), ('bank_transfer', 'Bank Transfer'), ('wallet_transfer', 'Wallet Transfer'), ('ewallet_transfer', 'eWallet Transfer'), ('ewallet_deposit', 'eWallet Deposit')], max_length=50)),
                ('transaction_id', models.CharField(default=apps.transactions.models.generate_transaction_id, max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('success', 'Successful'), ('errors', 'failed'), ('processing', 'Processing')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('network', models.CharField(max_length=10)),
                ('rec_name', models.CharField(default=None, max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_type', models.CharField(choices=[('bank_deposit', 'Bank Deposit'), ('card_deposit', 'Card Deposit'), ('ewallet_deposit', 'eWallet Deposit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('credit_card_number', models.CharField(max_length=50)),
                ('ewallet_name', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
