# Generated by Django 3.2.7 on 2023-07-26 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='Deposits',
        ),
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Transfers',
        ),
        migrations.AlterModelOptions(
            name='deposits',
            options={'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='mobile_topup',
            options={'verbose_name_plural': 'Mobile Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'All Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name_plural': 'Transfers'},
        ),
    ]
