# Generated by Django 3.2.7 on 2023-07-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230726_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='recipient',
            field=models.CharField(default='uncle', max_length=50),
        ),
    ]
