# Generated by Django 3.2.7 on 2023-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transfers_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='recipient',
            field=models.CharField(default='', max_length=50),
        ),
    ]
