# Generated by Django 3.2.7 on 2023-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transfers_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposits',
            old_name='bank_account_number',
            new_name='creditor_name',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='ewallet_name',
        ),
        migrations.RemoveField(
            model_name='mobile_topup',
            name='rec_name',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='ewallet_name',
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('wallet_deposit', 'Wallet Deposit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_deposit', 'Wallet Deposit'), ('bank_transfer', 'Bank Transfer'), ('wallet_transfer', 'Wallet Transfer'), ('mobile_purchase', 'Mobile Purchase')], max_length=50),
        ),
    ]
